services:
  woonstee-wordpress:
    image: registery.codeit.website/dewoonsteetiel
    environment:
      COMPOSER_AUTH: ${COMPOSER_AUTH}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      WP_ENV: ${WP_ENV}
      WP_HOME: ${WP_HOME}
      WP_SITEURL: ${WP_HOME}/wp
      AUTH_KEY: ${AUTH_KEY}
      SECURE_AUTH_KEY: ${SECURE_AUTH_KEY}
      LOGGED_IN_KEY: ${LOGGED_IN_KEY}
      NONCE_KEY: ${NONCE_KEY}
      AUTH_SALT: ${AUTH_SALT}
      SECURE_AUTH_SALT: ${SECURE_AUTH_SALT}
      LOGGED_IN_SALT: ${LOGGED_IN_SALT}
      NONCE_SALT: ${NONCE_SALT}
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - woonstee-mysql
    networks:
      - dokploy-network
    ports: 
      - "9000"

  woonstee-caddy:
    image: caddy:2
    ports:
      - "80"
    volumes: 
      - ./Caddyfile:/etc/caddy/Caddyfile
      - wordpress_data:/var/www/html
    depends_on:
      - woonstee-wordpress
    networks:
      - dokploy-network

  woonstee-mysql:
    image: mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - dokploy-network

  woonstee-phpmyadmin:
    image: arm64v8/phpmyadmin
    restart: always
    environment:
      PMA_HOST: woonstee-mysql
    depends_on:
      - woonstee-mysql
    ports:
      - "80"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    driver: bridge

volumes:
  mysql_data:
  wordpress_data: