name: Build Docker images
 
on:
  push:
    branches: ["master"]
 
jobs:
  build-and-push-dockerfile-image:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKERHUB_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Make sure to add the secrets in your repository in -> Settings -> Secrets (Actions) -> New repository secret
          password: ${{ secrets.DOCKERHUB_PASSWORD }}   # Make sure to add the secrets in your repository in -> Settings -> Secrets (Actions) -> New repository secret
 
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Make sure to replace with your own namespace and repository
          tags: |
            registery.codeit.website/dewoonsteetiel:latest
          platforms: linux/arm64
          build-args: |
            COMPOSER_AUTH=${{ secrets.COMPOSER_AUTH }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            WP_ENV=${{ secrets.WP_ENV }}
            WP_HOME=${{ secrets.WP_HOME }}
            WP_SITEURL=${{ secrets.WP_SITEURL }}
            AUTH_KEY=${{ secrets.AUTH_KEY }}
            SECURE_AUTH_KEY=${{ secrets.SECURE_AUTH_KEY }}
            LOGGED_IN_KEY=${{ secrets.LOGGED_IN_KEY }}
            NONCE_KEY=${{ secrets.NONCE_KEY }}
            AUTH_SALT=${{ secrets.AUTH_SALT }}
            SECURE_AUTH_SALT=${{ secrets.SECURE_AUTH_SALT }}
            LOGGED_IN_SALT=${{ secrets.LOGGED_IN_SALT }}
            NONCE_SALT=${{ secrets.NONCE_SALT }}